import "server-only";

// Development-only mock extraction provider. It exercises the pipeline —
// schema validation, provenance, review states, approval blocking — without
// any AI credential. Every value it produces is unmistakably marked as mock,
// and approval logic refuses quotes containing active mock rows.
import { EXTRACTION_SCHEMA_VERSION, type ExtractionOutput } from "./schema";

export const mockExtractionProvider = {
  name: "mock",
  model: null,
  promptVersion: "mock-v1",
  isMock: true,
  async extract(input: { fileName: string; category: string }): Promise<ExtractionOutput> {
    return {
      schema_version: EXTRACTION_SCHEMA_VERSION,
      project_metadata: { project_name: null, customer_name: null },
      drawing_metadata: { drawing_numbers: ["MOCK-001"], revisions: ["0"] },
      takeoff_items: [
        {
          item_mark: "MOCK-B1",
          category: "structural_steel",
          description: `[MOCK] Sample beam row generated for pipeline testing from ${input.fileName}`,
          material: "[MOCK] Steel",
          grade: null,
          profile: "[MOCK] W8x10",
          size: null,
          thickness: null,
          width: null,
          length: "[MOCK] 20 ft",
          quantity: 2,
          unit: "ea",
          unit_weight_lbs: null,
          linear_feet: null,
          holes: null,
          cuts: null,
          bends: null,
          welding: null,
          finish: null,
          notes: "[MOCK] This row was NOT read from your document.",
          source_page: null,
          drawing_number: "MOCK-001",
          drawing_revision: "0",
          evidence:
            "MOCK DATA — this row was generated by the development mock provider and was not read from your drawing.",
          confidence: "low",
        },
      ],
      handrail_total_linear_feet: null,
      ladder_total_linear_feet: null,
      finish_requirements: null,
      outside_vendor_needs: [],
      missing_information: [
        {
          question:
            "[MOCK] Example question generated by the development mock provider — real extraction is not connected.",
          category: "other",
          severity: "low",
        },
      ],
      warnings: [
        "MOCK extraction: no real document reading occurred. Connect a real provider before trusting any row.",
      ],
    };
  },
};
